import xlwings as xw
import time
app1 = xw.App(visible=True, add_book=False)
wb1 = app1.books.open(r"G:\Новое ОКК и УР\Мониторинг\Август 2022\Малая отчетность Август\Рабочее время ню.xlsm")
vba_macro = wb1.macro("RefreshPQ")
vba_macro()
time.sleep(15)
wb1.save()
wb1.close()
app1.quit()
app2 = xw.App(visible=True, add_book=False)
wb2 = app2.books.open(r"G:\Новое ОКК и УР\Мониторинг\Август 2022\Малая отчетность Август\Отчет по загрузке операторов ОИП.xlsm")
vba_macro = wb2.macro("RefreshPQ")
vba_macro()
time.sleep(15)
wb2.save()
wb2.close()
app2.quit()
app3 = xw.App(visible=True, add_book=False)
wb3 = app3.books.open(r"G:\Новое ОКК и УР\Мониторинг\Август 2022\Малая отчетность Август\Записи о Вызовах.xlsm")
vba_macro = wb3.macro("RefreshPQ")
vba_macro()
time.sleep(20)
wb3.save()
wb3.close()
app3.quit()
app4 = xw.App(visible=True, add_book=False)
wb4 = app4.books.open(r"G:\Новое Общие\Отдел Сервиса\Записи о Вызовах\Записи о Вызовах Август.xlsm")
vba_macro = wb4.macro("RefreshPQ")
vba_macro()
time.sleep(20)
wb4.save()
wb4.close()
app4.quit()
